services:
  - type: web_service
    name: postrace-api
    env: docker
    repo: https://github.com/bastiaanbrouwer77/PostRaceAnalysis
    branch: main
    rootDir: server_py
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web_service
    name: postrace-web
    env: docker
    repo: https://github.com/bastiaanbrouwer77/PostRaceAnalysis
    branch: main
    rootDir: client
    envVars:
      - key: REACT_APP_API_BASE
        value: https://postrace-api.onrender.com
